apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: titulacionacr.azurecr.io/mykeycloak:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://titulacion-db.postgres.database.azure.com:5432/proyecto_db
        - name: KC_DB_SCHEMA
          value: keycloak_schema
        - name: KC_DB_USERNAME
          value: administrador
        - name: KC_DB_PASSWORD
          value: rY7hSXu}s%NUHz!
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        args:
          - "start-dev"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
